FROM nvidia/cuda:10.2-devel-ubuntu18.04

# Install software
ENV DEBIAN_FRONTEND=noninteractive 

RUN apt-get update
RUN apt-get install -y git nano cmake libthrust-dev
WORKDIR /
RUN git clone https://github.com/GPUOpen-ProfessionalCompute-Tools/HIP
WORKDIR /HIP
RUN ./bin/hipconfig
RUN mkdir -p /opt/rocm/hip
RUN cp -a ./bin /opt/rocm/hip
RUN cp -a ./include /opt/rocm/hip
RUN cp -a ./cmake /opt/rocm/hip
RUN echo "// Auto-generated by cmake\n#ifndef HIP_VERSION_H\n#define HIP_VERSION_H\n#define HIP_VERSION_MAJOR 3\n#define HIP_VERSION_MINOR 5\n#define HIP_VERSION_PATCH 20126\n#define HIP_VERSION       (HIP_VERSION_MAJOR * 100 + HIP_VERSION_MINOR)\n#endif" >> /opt/rocm/hip/include/hip/hip_version.h

WORKDIR /root
CMD ["bash"]
